### ISSUE TITLE
Bug: Using Factory extension for create new object allocates new shared_ptr instances for depedencies

### ISSUE THREAD

**Issue by Shelim** [boost-ext/di#240]
I'm using both Factory and Scoped Scope extension in my project and I've run into following problem (removing Scoped Scope does *not* fix this)

When using Factory extension for creating new objects further in runtime, DI allocates new shared_ptr instances for depedencies. I am using Scoped Scope, because I need to have two distinct object trees during application run that uses the same classes but different instances. [Simplified and compilable source code included](https://github.com/boost-experimental/di/files/1431570/Source.zip). See following example:

    class interface_test
    {
    public:

        virtual int print_address() = 0;
    };

    class real_test : public interface_test
    {
    public:

        int print_address() final
        {
            return (int)(void*)this;
        }
    };

    class ifactorable
    {

    public:

        virtual int get_address() = 0;

    };

    class factorable : public ifactorable
    {
    public:

        factorable(std::shared_ptr<interface_test> test) : test(test)
        {

        }

        int get_address() final
        {
            return test->print_address();
        }

    private:

        std::shared_ptr<interface_test> test;
    };

    int main() {
        // clang-format off
        auto injector1 = di::make_injector(di::bind<interface_test>().in(scoped).to<real_test>()[boost::di::override]
            , di::bind<ifactorable>().in(scoped).to<factorable>()
            , di::bind<ifactory<ifactorable>>().to(factory<factorable>{})
        );

        auto injector2 = di::make_injector(di::bind<interface_test>().in(scoped).to<real_test>()[boost::di::override]
            , di::bind<ifactorable>().in(scoped).to<factorable>()
            , di::bind<ifactory<ifactorable>>().to(factory<factorable>{})
        );
        // clang-format on

        std::shared_ptr<ifactorable> ptr1 = injector1.create<std::shared_ptr<ifactorable>>();
        std::shared_ptr<ifactorable> ptr2 = injector1.create<std::shared_ptr<ifactorable>>();
        std::unique_ptr<ifactorable> ptr3 = injector1.create<std::unique_ptr<factorable>>();
        std::unique_ptr<ifactorable> ptr4 = injector1.create<const ifactory<ifactorable> & >().create();
        std::unique_ptr<ifactorable> ptr5 = injector1.create<const ifactory<ifactorable> & >().create();

        std::shared_ptr<ifactorable> ptr6 = injector2.create<std::shared_ptr<ifactorable>>();
        std::unique_ptr<ifactorable> ptr7 = injector2.create<const ifactory<ifactorable> & >().create();

        std::cout << "These should be equal!" << std::endl;
        std::cout << "ptr 1 = " << ptr1->get_address() << std::endl;
        std::cout << "ptr 2 = " << ptr2->get_address() << std::endl;
        std::cout << "ptr 3 = " << ptr3->get_address() << std::endl;
        std::cout << "ptr 4 = " << ptr4->get_address() << std::endl;
        std::cout << "ptr 5 = " << ptr5->get_address() << std::endl;
        std::cout << "These should be equal (but different from previous group)!" << std::endl;
        std::cout << "ptr 6 = " << ptr6->get_address() << std::endl;
        std::cout << "ptr 7 = " << ptr7->get_address() << std::endl;

        return 0;
    }

Sample output:

    These should be equal!
    ptr 1 = 5953696
    ptr 2 = 5953696
    ptr 3 = 5953696
    ptr 4 = 5958336
    ptr 5 = 5953744
    These should be equal (but different from previous group)!
    ptr 6 = 5954720
    ptr 7 = 5977712

**Comment by Shelim** [comment]
Used tool: Visual Studio 2015

**Comment by Shelim** [comment]
I can confirm the same happens in clang 6.0.0

**Comment by kanstantsin-chernik** [comment]
@Shelim I bumped into same issue. It happens because factory moves injector but don't move back.

**Comment by kanstantsin-chernik** [comment]
@Shelim there was merged PR. Can you check whether it fixed for you?

**Comment by kanstantsin-chernik** [comment]
I reproduced your problem:
```
  auto injector = di::make_injector( di::bind<interface>().to<implementation>().in(shared));
  auto inst1 = injector.create<std::shared_ptr<interface>>();
  auto injector1 = di::make_injector(std::move(injector));
  assert(inst1 == injector1.create<std::shared_ptr<interface>>());
```
Pool calls default constructor instead of move constructor.

**Comment by kanstantsin-chernik** [comment]
Fixed

**Comment by Shelim** [comment]
Thank you for your hard work, but I believe it is not yet fixed :-( Try to create factory object *again* in shared scope...

See following code:
[Source.zip - full content](https://github.com/boost-experimental/di/files/1531499/Source.zip)

	std::shared_ptr<ifactorable> ptr1 = injector1.create<std::shared_ptr<ifactorable>>();
	std::shared_ptr<ifactorable> ptr2 = injector1.create<std::shared_ptr<ifactorable>>();
	std::unique_ptr<ifactorable> ptr3 = injector1.create<std::unique_ptr<factorable>>();
	std::unique_ptr<ifactorable> ptr4 = injector1.create<const ifactory<ifactorable> & >().create();
	std::unique_ptr<ifactorable> ptr5 = injector1.create<const ifactory<ifactorable> & >().create();
	std::unique_ptr<ifactorable> ptr6 = injector1.create<const ifactory<ifactorable> & >().create();

	std::shared_ptr<ifactorable> ptr1b = injector2.create<std::shared_ptr<ifactorable>>();
	std::unique_ptr<ifactorable> ptr2b = injector2.create<const ifactory<ifactorable> & >().create();
	std::unique_ptr<ifactorable> ptr3b = injector2.create<const ifactory<ifactorable> & >().create();

	std::cout << "These should be equal!" << std::endl;
	std::cout << "ptr 1 = " << ptr1->get_address() << std::endl;
	std::cout << "ptr 2 = " << ptr2->get_address() << std::endl;
	std::cout << "ptr 3 = " << ptr3->get_address() << std::endl;
	std::cout << "ptr 4 = " << ptr4->get_address() << std::endl;
	std::cout << "ptr 5 = " << ptr5->get_address() << std::endl;
	std::cout << "ptr 6 = " << ptr6->get_address() << std::endl;
	std::cout << "These should be equal (but different from previous group)!" << std::endl;
	std::cout << "ptr 1b = " << ptr1b->get_address() << std::endl;
	std::cout << "ptr 2b = " << ptr2b->get_address() << std::endl;
	std::cout << "ptr 3b = " << ptr3b->get_address() << std::endl;

Sample output is:

	These should be equal!
	ptr 1 = 8903232
	ptr 2 = 8903232
	ptr 3 = 8903232
	ptr 4 = 8903232
	ptr 5 = 8902720
	ptr 6 = 8902832
	These should be equal (but different from previous group)!
	ptr 1b = 8902944
	ptr 2b = 8926352
	ptr 3b = 8926400

**Comment by kanstantsin-chernik** [comment]
@Shelim in sources you sent old version of factory. Update it and try again please.

**Comment by Shelim** [comment]
@kanstantsin-chernik 

Just tried it. Code attached: [Source.zip](https://github.com/boost-experimental/di/files/1532636/Source.zip)

Output is now:

    These should be equal!
    ptr 1 = 3987960
    ptr 2 = 3987960
    ptr 3 = 3987960
    ptr 4 = 3987960
    ptr 5 = 3987960
    ptr 6 = 3987960
    These should be equal (but different from previous group)!
    ptr 1b = 3991688
    ptr 2b = 3987960
    ptr 3b = 3987960

The second factory still used objects from first injector instance... :-(

**Comment by kanstantsin-chernik** [comment]
@Shelim you are right. At the moment factory has following line:
`static auto sp = std::make_shared<factory_impl<TInjector, T, typename TDependency::expected>>(injector);`

In addition singleton scope is also static variable. In next version it will be shared BTW.

You can have a look at shared_factory extension. It will help you I hope

**Comment by Shelim** [comment]
@kanstantsin-chernik 

Thanks for pointing it out,  I managed to code ugly workaround and now it works as it should have :-)

1. We need direct non-template parent for `ifactory` (or use `boost::any`)

```
    struct ifactory_base
    {
        virtual ~ifactory_base() noexcept = default;
    };

    template <class T, class... TArgs>
    struct ifactory : ifactory_base {
        virtual ~ifactory() noexcept = default;
        virtual std::unique_ptr<T> create(TArgs&&...) const = 0;
    };
```

2. Then we implement factory as:
```

    template <class T>
    struct factory {
        template <class TInjector, class TDependency>
        auto operator()(const TInjector& injector, const TDependency&) noexcept {
            auto iter = data_map.find(std::type_index(typeid(typename factory<T>::key_t<TInjector, TDependency>)));
            std::shared_ptr<ifactory_base> ret;
            if(iter == data_map.end()) {
                ret = std::make_shared<factory_impl<TInjector, T, typename TDependency::expected>>(injector);
                data_map.insert(std::make_pair(std::type_index(typeid(typename factory<T>::key_t<TInjector, TDependency>)), ret));
            }
            else
                ret = iter->second;
            return std::static_pointer_cast<factory_impl<TInjector, T, typename TDependency::expected>>(ret);
        }
    private:
        template <class T1, class T2> class key_t {};
        // Important! This is NOT static:
        std::unordered_map<std::type_index, std::shared_ptr<ifactory_base> > data_map;
    };
```

3. Then, finally, the output would be as it should be:

```
    These should be equal!
    ptr 1 = 7721680
    ptr 2 = 7721680
    ptr 3 = 7721680
    ptr 4 = 7721680
    ptr 5 = 7721680
    ptr 6 = 7721680
    These should be equal (but different from previous group)!
    ptr 1b = 7726392
    ptr 2b = 7726392
    ptr 3b = 7726392
```

[Full Source.zip](https://github.com/boost-experimental/di/files/1533136/Source.zip)

Thank you again for helping me out with that!

**Comment by swn1** [comment]
I've just wrestled my way through my first project with this lib and I have a problem related to this topic.  Specifically we have leak detection in our unit test framework and when an injector is specified to return a shared pointer it does not delete the "singleton" object until the end of time.  I see the "scoped" lifetime specification in this thread but it was not in the version of the documentation I was using so I need to go back and fill in my reading.  But I'd like to see the end of the lifetime of an injector release all of the resources it owns.  If that's not already in scope (ha ha) should I enter an new ticket?

**Comment by kris-jusiak** [comment]
It's not mainstream yet but it can be achieved using scopes.shared extension.
Please, take a look:
https://github.com/boost-experimental/di/blob/cpp14/extension/include/boost/di/extension/scopes/shared.hpp
https://github.com/boost-experimental/di/blob/cpp14/extension/test/scopes/shared.cpp

Shared scope lifetime is bound to the injector itself, so all deps are going to die with it too.
